// src/context/LanguageContext.jsx
import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

// All translations
const translations = {
  en: {
    // Common
    appName: "AgriVistaar",
    tagline: "Your Farming Companion",
    precisionAg: "Precision agriculture • Drone analytics",
    login: "Login",
    signup: "Sign Up",
    welcome: "Hello, Farmer 👋",
    welcomeFarmer: "Hello, Farmer",
    requiredField: "Required",
    passwordMismatch: "Passwords do not match",
    wrongPassword: "Wrong password",
    userNotFound: "User not found",
    userAlreadyExists: "User already exists",
    signupFailed: "Signup failed. Please try again.",
    loginFailed: "Login failed. Please try again.",
    loadError: "Failed to load dashboard",
    loading: "Loading...",
    scanSubmitError: "Scan request failed. Please try again.",
dropImageHere: "Drop drone image here",
dropImageOr: "or",
browseLink: "browse",
dropImageToSelect: "to select",
supportedFormats: "Supported: JPG, PNG, WEBP",
orDivider: "OR",
chooseFileButton: "Choose File",
analyzingStatus: "Analyzing...",
analysisResultTitle: "Analysis Result",
removeFile: "Remove",
resCropHealth: "Crop Health",
resRiskLevel: "Risk Level",
resNdvi: "NDVI Score",
resAffectedArea: "Affected Area",
resRecommendation: "Recommendation",
resDiseases: "Diseases Detected",
resAnomalies: "Anomalies",
infoCropHealth: "Crop Health",
infoCropHealthDesc: "NDVI Analysis",
infoPestDetection: "Pest Detection",
infoPestDetectionDesc: "AI Scan",
infoMoisture: "Moisture Map",
infoMoistureDesc: "Stress Zones",
 

    // Fields & Scans
    myFieldsTitle: "My fields",
    myFieldsHelp: "Tap a field to see its scan status and details.",
    noFields: "No fields yet.",
    fieldCrop: "Crop:",
    lastScan: "Last scan:",
    notScanned: "Not yet scanned",
    myScansTitle: "My drone scans",
    myScansHelp: "History of your recent scans. Tap any row to view full report.",
    noScans: "No scans yet.",
    fieldFallback: "Field",
    analysisPendingShort: "Analysis pending",
    lastScanTitle: "Last scan",
    lastScanField: "Field:",
    lastScanStatus: "Status:",
    lastScanDate: "Date:",
    analysisPendingLong:
      "Analysis pending. Report will be ready after images upload / processing.",
    tapToViewReport: "Tap to view full report",
    requested: "Scan requested",
    imagesUploaded: "Analysis in progress",
    completed: "Report ready",
    unknownStatus: "Unknown status",

    // AI / Chat
    mainSathi: "AgriBuddy — Your Farming Assistant",
    cropHealth: "Crop health & pest problems",
    droneScan: "Drone scan reports",
    useApp: "Use app in",
    selectLang: "Choose language — Hindi, English, or others",

    // Calculator
    calculateButton: "Crop Profit Calculator",
    allFieldsRequired: "Please fill in all fields.",
    positiveValuesRequired: "All values must be greater than 0.",
    totalYieldLabel: "Total Yield",
    totalRevenueLabel: "Total Revenue",
    totalCostLabel: "Total Cost",
    netProfitLabel: "Net Profit",
    quintalUnit: "quintal",
    profitCalculatorHint:
      "Estimate based on expected mandi prices. Actual results may vary.",
    analysisCompleteMessage:
      "Field analysis complete! Check your dashboard for results.",
    profitCalculatorTitle: "Crop Profit Calculator",
    profitCalculatorDesc: "Estimate yield, revenue and profit for your crop.",
    areaPlaceholder: "Area (acre)",
    totalCostPlaceholder: "Total cost (₹)",
    expectedPricePlaceholder: "Expected market price (₹ per quintal)",
    predictedYieldPlaceholder: "Predicted yield (quintal per acre)",

    // GetStarted Page
    getStarted: "Get Started",
    createAccount: "Create free account",
    heroText:
      "See pests, nutrient stress and yield from the sky, and know the best time and mandi to sell your crop for maximum profit.",
    droneInsights: "Drone insights",
    droneInsightsDesc: "Detect pests & stress early",
    mandiTiming: "Smart market timing",
    mandiTimingDesc: "Sell when prices are highest",
    yieldPrediction: "Yield prediction",
    yieldPredictionDesc: "Plan harvest perfectly",
    farmers: "Farmers",
    acresMonitored: "Acres monitored",
    accuracy: "Accuracy",
    aiSupport: "AI Support",
    liveMonitoring: "Live monitoring",
    updatedAgo: "Updated 2h ago",
    droneView: "Drone view of crop field",
    aiPowered: "(AI-powered analysis)",
    pestRisk: "Pest risk",
    nutrient: "Nutrient",
    yield: "Yield",
    low: "Low",
    onArea: "on 80% area",
    mediumN: "Medium N",
    stressNorth: "stress in north",
    perAcre: "per acre",

    // Login Page
    loginTo: "Login to",
    phone: "Phone number / Email",
    phonePlaceholder: "Enter phone number or email",
    password: "Password / OTP",
    passwordPlaceholder: "••••••",
    forgotPassword: "Forgot password?",
    support: "Support: 1800-XXX-XXXX",
    newTo: "New to",
    loginDesc:
      "Use your registered phone or email to see drone scans, crop health and mandi signals tailored to your farm.",

    // Signup Page
    join: "Join",
    newFarmerAccount: "New farmer account",
    signupDesc:
      "Get AI-powered pest alerts, nutrient stress maps and mandi timing suggestions for your fields.",
    name: "Name",
    namePlaceholder: "Farmer name",
    phoneNumber: "Phone number / Email",
    phoneDesc: "For OTP, login and crop alerts",
    district: "District",
    districtPlaceholder: "e.g. Sitapur",
    state: "State",
    statePlaceholder: "Uttar Pradesh",
    passwordLabel: "Password",
    passwordSignupPlaceholder: "Choose a strong password",
    createAccountBtn: "Create account",
    agreeText:
      "By signing up you agree to receive important crop alerts on your mobile number or email.",
    alreadyHaveAccount: "Already have an account?",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordPlaceholder: "Re-enter password",

    // Home/Dashboard
    dashboardTitle: "Farmer Drone Dashboard",
    farmerDroneDashboard: "Farmer Drone Dashboard",
    todaySnapshot:
      "Here is today's snapshot of your fields, health and income.",
    droneUpdated:
      "Drone scan updated 2 hours ago • Weather: Good for spraying",
    totalFields: "Total fields",
    atRiskFields: "At-risk fields",
    avgYield: "Avg yield (q/acre)",
    expectedIncome: "Expected income (₹)",
    myFields: "My fields",
    addNewField: "Add new field",
    clickField: "Click a field card to open its drone health map & yield.",
    wheatNorth: "North wheat field",
    moderatePestRisk: "Moderate pest risk",
    mustardEast: "Mustard – East plot",
    healthy: "Healthy",
    paddySouth: "Lowland paddy",
    nutrientStress: "Nutrient stress",
    todayMandi: "Today's market signal",
    mandiDesc: "Based on last 30 days market data and predicted prices.",
    wheat: "Wheat",
    sellNow: "Sell now ↑",
    mustard: "Mustard",
    hold1Week: "Hold 1 week",
    paddy: "Paddy",
    priceFalling: "Price falling ↓",
    logout: "Logout",
    dashboard: "Dashboard",
    droneUpload: "Drone Upload",
    profit: "Profit",
    healthyCropLabel: "Healthy crop",
    cropLabel: "Crop:",
    sowingDateLabel: "Sowing date:",
    myScans: "My scans",

    // Scan timing
    scanGeneralTip:
      "Conduct high-value drone scans only at 2–3 critical stages of the season; no need to fly a drone every week.",
    scanRecommendedPrefix: "Scan recommended this week for ",
    scanRecommendedSuffix: " (key growth stage).",
    scansThisSeason: "{{done}}/{{total}} scans this season",
    scanDueNow: "Scan due now ({{stage}} stage)",
    nextScanInDays: "Next scan: {{stage}} in ~{{days}} days",

    // Field detail
    fieldNotFound: "Field not found.",
    requestScanButton: "Request drone scan",
    viewLastScanButton: "View last scan report",
    analyzeFieldButton: "Analyze field",
    fieldDetailTitlePrefix: "Field #",
    fieldDetailTitleSuffix: "– Health & Yield",
    openProfitCalculator: "Open profit calculator",
    fieldHealthy: "Healthy crop",
    newFieldName: "New Plot",

    // Request scan form
    requestScanTitle: "Request a drone scan",
    requestScanDesc:
      "Select which field and crop stage you want to scan. This request will go to your FPO / drone operator.",
    fieldLabel: "Field",
    selectFieldPlaceholder: "Enter or confirm field name / ID",
    fieldRequired: "Please enter the field name or ID.",
    stageLabel: "Crop stage",
    cropStageLabel: "Crop stage",
    selectStagePlaceholder: "Select crop stage",
    stageEarly: "Early growth",
    stageMid: "Mid-season",
    stagePreHarvest: "Pre-harvest",
    stageRequired: "Please select a crop stage.",
    dateLabel: "Preferred scan date",
    dateRequired: "Please choose a date.",
    preferredDateLabel: "Preferred date",
    notesLabel: "Notes for drone pilot",
    notesPlaceholder: "Describe any visible issues or instructions (optional)",
    pilotNotesLabel: "Notes for pilot (optional)",
    scanRequestSuccess: "Your drone scan request has been submitted.",
    submitScanRequest: "Submit scan request",
    submitScanButton: "Submit scan request",

    // Last scan report
    lastScanDesc:
      "See the latest drone images, pest risk, nutrient stress and yield estimate for your fields.",
    healthSummaryTitle: "Health summary",
    yieldPredictionTitle: "Yield prediction",
    pestRiskMedium: "Pest risk: Medium (patches in north side)",
    nutrientStressLow: "Nutrient stress: Low",
    expectedYieldLine: "Expected yield: 22–26 q/acre",
    profitHint:
      "Use Profit calculator page to see expected income and profit for this yield.",
    dronePlaceholder: "Drone image / NDVI map placeholder",

    homeTitle: "Your fields",

    // Calculator, upload, chat, forgot password
    uploadDroneTitle: "Upload Drone Images",
    uploadDroneDesc:
      "Send field images to AI for pest, stress and yield analysis.",
    aiAssistantTitle: "AI Farm Assistant",
    chatWelcome: "Hello! Ask me about your crop, yield or prices.",
    chatDemoReply: "Demo reply: I will analyze your field and prices.",
    chatPlaceholder: "Type your question in English/Hindi...",
    send: "Send",
    askSathi: "Ask AgriBuddy",
    forgotPasswordTitle: "Forgot password?",
    forgotPasswordDesc: "Create a new password for your AgriVistaar account.",
    saveNewPassword: "Save new password",

    // Scan tip
    criticalScanTip:
      "Get scans done at critical stages: at the beginning, mid-crop stage, and before harvest.",
  },

  hi: {
    // Common
    appName: "एग्रीविस्तार",
    tagline: "किसान का साथी",
    precisionAg: "सटीक कृषि • ड्रोन विश्लेषण",
    login: "लॉगिन",
    signup: "साइन अप",
    welcome: "नमस्ते, किसान जी 👋",
    welcomeFarmer: "नमस्ते, किसान जी",
    requiredField: "अनिवार्य है",
    passwordMismatch: "पासवर्ड मेल नहीं खा रहे हैं",
    wrongPassword: "गलत पासवर्ड",
    userNotFound: "उपयोगकर्ता नहीं मिला",
    userAlreadyExists: "उपयोगकर्ता पहले से मौजूद है",
    signupFailed: "साइनअप असफल रहा, कृपया दोबारा कोशिश करें।",
    loginFailed: "लॉगिन असफल रहा, कृपया दोबारा कोशिश करें।",
    loadError: "डैशबोर्ड लोड नहीं हो पाया",
    loading: "लोड हो रहा है...",
    scanSubmitError: "स्कैन अनुरोध विफल रहा। कृपया दोबारा प्रयास करें।",

    // AI / Chat
    mainSathi: "कृषि साथी — आपका खेती सहायक",
    cropHealth: "फसल स्वास्थ्य एवं कीट समस्या",
    droneScan: "ड्रोन स्कैन रिपोर्ट",
    useApp: "ऐप भाषा में उपयोग",
    selectLang: "भाषा चुनें — हिंदी, अंग्रेजी, अन्य",

    // Calculator
    calculateButton: "फसल लाभ कैलकुलेटर",
    allFieldsRequired: "कृपया सभी फ़ील्ड भरें।",
    positiveValuesRequired: "सभी मान 0 से अधिक होने चाहिए।",
    totalYieldLabel: "कुल उपज",
    totalRevenueLabel: "कुल आमदनी",
    totalCostLabel: "कुल लागत",
    netProfitLabel: "शुद्ध मुनाफा",
    quintalUnit: "क्विंटल",
    profitCalculatorHint:
      "अनुमानित मंडी भाव पर आधारित। वास्तविक परिणाम भिन्न हो सकते हैं।",
    analysisCompleteMessage: "खेत का विश्लेषण पूरा हुआ! परिणाम डैशबोर्ड पर देखें।",
    profitCalculatorTitle: "फसल लाभ कैलकुलेटर",
    profitCalculatorDesc: "अपनी फसल की उपज, आमदनी और लाभ का अनुमान लगाएं।",
    areaPlaceholder: "क्षेत्रफल (एकड़)",
    totalCostPlaceholder: "कुल लागत (₹)",
    expectedPricePlaceholder: "अपेक्षित मंडी कीमत (₹ प्रति क्विंटल)",
    predictedYieldPlaceholder: "अनुमानित उपज (क्विंटल प्रति एकड़)",

    // GetStarted Page
    getStarted: "शुरू करें",
    createAccount: "मुफ्त खाता बनाएं",
    heroText:
      "आकाश से कीट, पोषक तनाव और उपज देखें, और अधिकतम लाभ के लिए अपनी फसल बेचने का सबसे अच्छा समय और मंडी जानें।",
    droneInsights: "ड्रोन जानकारी",
    droneInsightsDesc: "कीटों और तनाव का जल्दी पता लगाएं",
    mandiTiming: "स्मार्ट मंडी समय",
    mandiTimingDesc: "जब कीमतें सबसे अधिक हों तब बेचें",
    yieldPrediction: "उपज पूर्वानुमान",
    yieldPredictionDesc: "फसल की सही योजना बनाएं",
    farmers: "किसान",
    acresMonitored: "एकड़ निगरानी",
    accuracy: "सटीकता",
    aiSupport: "एआई सहायता",
    liveMonitoring: "लाइव निगरानी",
    updatedAgo: "2 घंटे पहले अपडेट किया गया",
    droneView: "फसल के खेत का ड्रोन दृश्य",
    aiPowered: "(एआई-संचालित विश्लेषण)",
    pestRisk: "कीट जोखिम",
    nutrient: "पोषक तत्व",
    yield: "उपज",
    low: "कम",
    onArea: "80% क्षेत्र पर",
    mediumN: "मध्यम नाइट्रोजन",
    stressNorth: "उत्तर में तनाव",
    perAcre: "प्रति एकड़",

    // Login Page
    loginTo: "लॉगिन करें",
    phone: "फोन नंबर / ईमेल",
    phonePlaceholder: "फोन नंबर या ईमेल दर्ज करें",
    password: "पासवर्ड / OTP",
    passwordPlaceholder: "••••••",
    forgotPassword: "पासवर्ड भूल गए?",
    support: "सहायता: 1800-XXX-XXXX",
    newTo: "नए हैं",
    loginDesc:
      "अपने पंजीकृत फोन या ईमेल से ड्रोन स्कैन, फसल स्वास्थ्य और मंडी संकेत देखें।",

    // Signup Page
    join: "शामिल हों",
    newFarmerAccount: "नया किसान खाता",
    signupDesc:
      "अपने खेतों के लिए AI-संचालित कीट अलर्ट, पोषक तनाव मानचित्र और मंडी समय सुझाव प्राप्त करें।",
    name: "नाम",
    namePlaceholder: "किसान का नाम",
    phoneNumber: "फोन नंबर / ईमेल",
    phoneDesc: "OTP, लॉगिन और फसल अलर्ट के लिए",
    district: "जिला",
    districtPlaceholder: "जैसे सीतापुर",
    state: "राज्य",
    statePlaceholder: "उत्तर प्रदेश",
    passwordLabel: "पासवर्ड",
    passwordSignupPlaceholder: "एक मजबूत पासवर्ड चुनें",
    createAccountBtn: "खाता बनाएं",
    agreeText:
      "साइन अप करके आप अपने मोबाइल नंबर या ईमेल पर महत्वपूर्ण फसल अलर्ट प्राप्त करने के लिए सहमत हैं।",
    alreadyHaveAccount: "पहले से खाता है?",
    confirmPasswordLabel: "पासवर्ड की पुष्टि करें",
    confirmPasswordPlaceholder: "पासवर्ड दोबारा लिखें",

    // Home/Dashboard
    dashboardTitle: "किसान ड्रोन डैशबोर्ड",
    farmerDroneDashboard: "किसान ड्रोन डैशबोर्ड",
    todaySnapshot:
      "यहां आपके खेतों, स्वास्थ्य और आय का आज का स्नैपशॉट है।",
    droneUpdated:
      "ड्रोन स्कैन 2 घंटे पहले अपडेट किया गया • मौसम: छिड़काव के लिए अच्छा",
    totalFields: "कुल खेत",
    atRiskFields: "जोखिम वाले खेत",
    avgYield: "औसत उपज (क्विंटल/एकड़)",
    expectedIncome: "अपेक्षित आय (₹)",
    myFields: "मेरे खेत",
    addNewField: "नया खेत जोड़ें",
    clickField:
      "ड्रोन स्वास्थ्य मानचित्र और उपज खोलने के लिए खेत कार्ड पर क्लिक करें।",
    wheatNorth: "उत्तर गेहूं का खेत",
    moderatePestRisk: "मध्यम कीट जोखिम",
    mustardEast: "सरसों – पूर्व प्लॉट",
    healthy: "स्वस्थ",
    paddySouth: "नीचला धान का खेत",
    nutrientStress: "पोषक तनाव",
    todayMandi: "आज का मंडी संकेत",
    mandiDesc:
      "पिछले 30 दिनों के मंडी डेटा और अनुमानित कीमतों के आधार पर।",
    wheat: "गेहूं",
    sellNow: "अभी बेचें ↑",
    mustard: "सरसों",
    hold1Week: "1 सप्ताह रुकें",
    paddy: "धान",
    priceFalling: "कीमत गिर रही है ↓",
    logout: "लॉगआउट",
    dashboard: "डैशबोर्ड",
    droneUpload: "ड्रोन अपलोड",
    profit: "मुनाफ़ा",
    myScans: "मेरे स्कैन",
    lastScan: "आखिरी स्कैन",

    // Fields & Scans
    myFieldsTitle: "मेरे खेत",
    myFieldsHelp:
      "किसी खेत पर टैप करके उसका स्कैन स्टेटस और डिटेल्स देखें।",
    noFields: "अभी कोई खेत जोड़ा नहीं गया है।",
    fieldCrop: "फसल:",
    lastScanLabel: "आखिरी स्कैन:",
    notScanned: "अभी तक स्कैन नहीं हुआ",
    myScansTitle: "मेरे ड्रोन स्कैन",
    myScansHelp:
      "आपके हाल के सभी ड्रोन स्कैन की लिस्ट। पूरी रिपोर्ट के लिए किसी पंक्ति पर टैप करें।",
    noScans: "अभी तक कोई स्कैन नहीं हुआ।",
    fieldFallback: "खेत",
    analysisPendingShort: "विश्लेषण जारी है",
    lastScanTitle: "आखिरी स्कैन",
    lastScanField: "खेत:",
    lastScanStatus: "स्थिति:",
    lastScanDate: "तारीख:",
    analysisPendingLong:
      "विश्लेषण जारी है। तस्वीरें अपलोड और प्रोसेस होने के बाद रिपोर्ट तैयार होगी।",
    tapToViewReport: "पूरी रिपोर्ट देखने के लिए टैप करें",
    requested: "स्कैन अनुरोध किया गया",
    imagesUploaded: "विश्लेषण जारी है",
    completed: "रिपोर्ट तैयार",
    unknownStatus: "स्थिति अज्ञात",

    // Field detail
    healthyCropLabel: "फसल की स्थिति: स्वस्थ",
    cropLabel: "फसल:",
    sowingDateLabel: "बुवाई की तारीख:",
    requestScanButton: "ड्रोन स्कैन का अनुरोध करें",
    fieldNotFound: "खेत नहीं मिला।",
    viewLastScanButton: "पिछली स्कैन रिपोर्ट देखें",
    analyzeFieldButton: "खेत की जाँच करें",
    fieldDetailTitlePrefix: "फील्ड #",
    fieldDetailTitleSuffix: "– स्वास्थ्य और उपज",
    openProfitCalculator: "प्रॉफिट कैलकुलेटर खोलें",
    fieldHealthy: "स्वस्थ फसल",
    newFieldName: "नया प्लॉट",
dropImageHere: "ड्रोन चित्र यहाँ छोड़ें",
dropImageOr: "या",
browseLink: "ब्राउज़ करें",
dropImageToSelect: "करके चुनें",
supportedFormats: "समर्थित: JPG, PNG, WEBP",
orDivider: "या",
chooseFileButton: "फ़ाइल चुनें",
analyzingStatus: "विश्लेषण हो रहा है...",
analysisResultTitle: "विश्लेषण परिणाम",
removeFile: "हटाएं",
resCropHealth: "फसल स्वास्थ्य",
resRiskLevel: "जोखिम स्तर",
resNdvi: "NDVI स्कोर",
resAffectedArea: "प्रभावित क्षेत्र",
resRecommendation: "सुझाव",
resDiseases: "कवर की गई बीमारियां",
resAnomalies: "खामियां",
infoCropHealth: "फसल स्वास्थ्य",
infoCropHealthDesc: "एनडीवीआई (NDVI) विश्लेषण",
infoPestDetection: "कीट पहचान",
infoPestDetectionDesc: "एआई स्कैन",
infoMoisture: "नमी मानचित्र",
infoMoistureDesc: "तनाव क्षेत्र",
    // Request scan form
    requestScanTitle: "ड्रोन स्कैन का अनुरोध करें",
    requestScanDesc:
      "कौन‑सा खेत और फसल चरण स्कैन करवाना है चुनें। यह अनुरोध आपके एफपीओ / ड्रोन ऑपरेटर को जाएगा।",
    fieldLabel: "खेत",
    selectFieldPlaceholder: "खेत का नाम या आईडी लिखें / पुष्टि करें",
    fieldRequired: "कृपया खेत का नाम या आईडी भरें।",
    stageLabel: "फसल की अवस्था",
    cropStageLabel: "फसल का चरण",
    selectStagePlaceholder: "फसल की अवस्था चुनें",
    stageEarly: "शुरुआती वृद्धि",
    stageMid: "मध्य अवस्था",
    stagePreHarvest: "कटाई से पहले",
    stageRequired: "कृपया फसल की अवस्था चुनें।",
    dateLabel: "पसंदीदा स्कैन की तारीख",
    dateRequired: "कृपया तारीख चुनें।",
    preferredDateLabel: "पसंदीदा तिथि",
    notesLabel: "ड्रोन पायलट के लिए नोट्स",
    notesPlaceholder:
      "कोई दिखने वाली समस्या या खास निर्देश लिखें (वैकल्पिक)।",
    pilotNotesLabel: "पायलट के लिए नोट (वैकल्पिक)",
    scanRequestSuccess: "आपका ड्रोन स्कैन अनुरोध भेज दिया गया है।",
    submitScanRequest: "स्कैन अनुरोध सबमिट करें",
    submitScanButton: "स्कैन अनुरोध भेजें",

    // Last scan report
    lastScanDesc:
      "अपने खेतों के लिए ताज़ा ड्रोन चित्र, कीट जोखिम, पोषक तनाव और उपज अनुमान देखें।",
    lastScanAnalysis:
      "हल्का तनाव लगभग 18% क्षेत्र में पाया गया, ज़्यादातर उत्तरी हिस्से में। 3 दिनों के भीतर नाइट्रोजन स्प्रे की सिफ़ारिश की जाती है।",
    healthSummaryTitle: "स्वास्थ्य सारांश",
    yieldPredictionTitle: "उपज अनुमान",
    pestRiskMedium: "कीट जोखिम: मध्यम (उत्तर हिस्से में पैच)",
    nutrientStressLow: "पोषक तनाव: कम",
    expectedYieldLine: "अनुमानित उपज: 22–26 क्विंटल/एकड़",
    profitHint:
      "इस उपज के लिए अपेक्षित आय और मुनाफ़ा देखने के लिए लाभ कैलकुलेटर पेज का उपयोग करें।",
    dronePlaceholder: "ड्रोन छवि / NDVI मानचित्र प्लेसहोल्डर",
    homeTitle: "आपके खेत",

    // Scan timing
    scanGeneralTip:
      "सीज़न के केवल 2–3 ज़रूरी चरणों पर ही ड्रोन स्कैन करवाएं; हर सप्ताह ड्रोन उड़ाने की ज़रूरत नहीं है।",
    scanRecommendedPrefix: "इस सप्ताह स्कैन की सलाह: ",
    scanRecommendedSuffix: " (महत्वपूर्ण वृद्धि चरण)।",
    scansThisSeason: "{{done}}/{{total}} स्कैन इस सीज़न में",
    scanDueNow: "स्कैन अभी करें ({{stage}} चरण)",
    nextScanInDays: "अगला स्कैन: {{stage}} लगभग {{days}} दिन में",

    // Calculator, upload, chat, forgot password
    uploadDroneTitle: "ड्रोन चित्र अपलोड करें",
    uploadDroneDesc:
      "कीट, तनाव और उपज विश्लेषण के लिए खेत की तस्वीरें भेजें।",
    aiAssistantTitle: "एआई खेती सहायक",
    chatWelcome:
      "नमस्ते! अपनी फसल, उपज या मंडी कीमतों के बारे में पूछें।",
    chatDemoReply: "डेमो जवाब: मैं आपके खेत और कीमतों का विश्लेषण करूंगा।",
    chatPlaceholder: "अपना सवाल हिंदी/अंग्रेज़ी में लिखें...",
    send: "भेजें",
    askSathi: "साथी से पूछें",
    forgotPasswordTitle: "पासवर्ड भूल गए?",
    forgotPasswordDesc:
      "अपने एग्रीविस्तार खाते के लिए नया पासवर्ड बनाएं।",
    saveNewPassword: "नया पासवर्ड सेव करें",

    // Scan tip
    criticalScanTip:
      "सिर्फ ज़रूरी चरणों पर ही स्कैन करवाएं: शुरुआत, बीच की फसल और कटाई से पहले।",

    scanItemCompleted: "पूर्ण",
    scanItemRequested: "अनुरोधित",
  },

  ta: {
    appName: "AgriVistaar",
    tagline: "விவசாயியின் தோழர்",
    precisionAg: "துல்லியமான விவசாயம் • ட்ரோன் பகுப்பாய்வு",
    login: "உள்நுழைய",
    signup: "பதிவு செய்ய",
    newFieldName: "புதிய நிலம்",
    welcome: "வணக்கம், விவசாயி அய்யா 👋",
    welcomeFarmer: "வணக்கம், விவசாயி அய்யா",
    requiredField: "தேவையான புலம்",
    passwordMismatch: "கடவுச்சொற்கள் பொருந்தவில்லை",
    wrongPassword: "தவறான கடவுச்சொல்",
    userNotFound: "பயனர் கண்டுபிடிக்கப்படவில்லை",
    userAlreadyExists: "பயனர் ஏற்கனவே உள்ளார்",
    signupFailed: "பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
    loginFailed: "உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
    loadError: "டாஷ்போர்டை ஏற்ற முடியவில்லை",
    loading: "ஏற்றப்படுகிறது...",
    scanSubmitError: "ஸ்கேன் கோரிக்கை தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
    getStarted: "தொடங்குங்கள்",
    createAccount: "இலவச கணக்கை உருவாக்கவும்",
    heroText: "வானத்திலிருந்து பூச்சிகள், ஊட்டச்சத்து அழுத்தம் மற்றும் விளைச்சலைப் பார்க்கவும், அதிகபட்ச லாபத்திற்காக உங்கள் பயிரை விற்க சிறந்த நேரம் மற்றும் சந்தையை அறியவும்.",
    droneInsights: "ட்ரோன் நுண்ணறிவு",
    droneInsightsDesc: "பூச்சிகள் மற்றும் அழுத்தத்தை ஆரம்பத்திலேயே கண்டறியவும்",
    mandiTiming: "புத்திசாலித்தனமான சந்தை நேரம்",
    mandiTimingDesc: "விலைகள் அதிகமாக இருக்கும்போது விற்கவும்",
    yieldPrediction: "விளைச்சல் கணிப்பு",
    yieldPredictionDesc: "அறுவடையை சரியாக திட்டமிடுங்கள்",
    farmers: "விவசாயிகள்",
    acresMonitored: "ஏக்கர் கண்காணிக்கப்பட்டது",
    accuracy: "துல்லியம்",
    aiSupport: "AI ஆதரவு",
    liveMonitoring: "நேரடி கண்காணிப்பு",
    updatedAgo: "2 மணி நேரத்திற்கு முன் புதுப்பிக்கப்பட்டது",
    droneView: "பயிர் வயலின் ட்ரோன் காட்சி",
    aiPowered: "(AI-இயங்கும் பகுப்பாய்வு)",
    pestRisk: "பூச்சி ஆபத்து",
    nutrient: "ஊட்டச்சத்து",
    yield: "விளைச்சல்",
    low: "குறைவு",
    onArea: "80% பகுதியில்",
    mediumN: "நடுத்தர N",
    stressNorth: "வடக்கில் அழுத்தம்",
    perAcre: "ஒரு ஏக்கருக்கு",
    loginTo: "உள்நுழைய",
    phone: "தொலைபேசி எண் / மின்னஞ்சல்",
    phonePlaceholder: "தொலைபேசி எண் அல்லது மின்னஞ்சலை உள்ளிடவும்",
    password: "கடவுச்சொல் / OTP",
    passwordPlaceholder: "••••••",
    forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    support: "ஆதரவு: 1800-XXX-XXXX",
    newTo: "புதியவரா",
    loginDesc: "உங்கள் பண்ணைக்கு ஏற்ற ட்ரோன் ஸ்கேன்கள், பயிர் ஆரோக்கியம் மற்றும் சந்தை சமிக்ஞைகளைப் பார்க்க உங்கள் பதிவு செய்யப்பட்ட தொலைபேசி அல்லது மின்னஞ்சலைப் பயன்படுத்தவும்.",
    join: "சேரவும்",
    newFarmerAccount: "புதிய விவசாயி கணக்கு",
    signupDesc: "உங்கள் வயல்களுக்கு AI-இயங்கும் பூச்சி எச்சரிக்கைகள், ஊட்டச்சத்து அழுத்த வரைபடங்கள் மற்றும் சந்தை நேர பரிந்துரைகளைப் பெறுங்கள்.",
    name: "பெயர்",
    namePlaceholder: "விவசாயியின் பெயர்",
    phoneNumber: "தொலைபேசி எண் / மின்னஞ்சல்",
    phoneDesc: "OTP, உள்நுழைவு மற்றும் பயிர் எச்சரிக்கைகளுக்கு",
    district: "மாவட்டம்",
    districtPlaceholder: "எ.கா. சீதாபூர்",
    state: "மாநிலம்",
    statePlaceholder: "உத்தரபிரதேசம்",
    passwordLabel: "கடவுச்சொல்",
    passwordSignupPlaceholder: "வலுவான கடவுச்சொல்லைத் தேர்ந்தெடுக்கவும்",
    createAccountBtn: "கணக்கை உருவாக்கவும்",
    agreeText: "பதிவு செய்வதன் மூலம் உங்கள் மொபைல் எண் அல்லது மின்னஞ்சலில் முக்கியமான பயிர் எச்சரிக்கைகளைப் பெற ஒப்புக்கொள்கிறீர்கள்.",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    confirmPasswordLabel: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    confirmPasswordPlaceholder: "கடவுச்சொல்லை மீண்டும் உள்ளிடவும்",
    todaySnapshot: "இன்று உங்கள் வயல்கள், ஆரோக்கியம் மற்றும் வருமானத்தின் விரைவு காட்சி இங்கே உள்ளது.",
    droneUpdated: "ட்ரோன் ஸ்கேன் 2 மணி நேரத்திற்கு முன் புதுப்பிக்கப்பட்டது • வானிலை: தெளிப்பதற்கு நல்லது",
    totalFields: "மொத்த வயல்கள்",
    atRiskFields: "ஆபத்தில் உள்ள வயல்கள்",
    avgYield: "சராசரி விளைச்சல் (குவிண்டால்/ஏக்கர்)",
    expectedIncome: "எதிர்பார்க்கப்படும் வருமானம் (₹)",
    myFields: "என் நிலங்கள்",
    addNewField: "புதிய வயலைச் சேர்க்கவும்",
    clickField: "ட்ரோன் ஆரோக்கிய வரைபடம் மற்றும் விளைச்சல் பார்க்க, ஒரு நிலத்தைத் தொட்டு திறக்கவும்.",
    wheatNorth: "வட கோதுமை வயல்",
    moderatePestRisk: "நடுத்தர பூச்சி ஆபத்து",
    mustardEast: "கடுகு – கிழக்கு நிலம்",
    healthy: "ஆரோக்கியமானது",
    paddySouth: "தாழ்நில நெல்",
    nutrientStress: "ஊட்டச்சத்து அழுத்தம்",
    todayMandi: "இன்றைய சந்தை சமிக்ஞை",
    mandiDesc: "கடந்த 30 நாட்கள் சந்தை தரவு மற்றும் கணிக்கப்பட்ட விலைகளின் அடிப்படையில்.",
    wheat: "கோதுமை",
    sellNow: "இப்போது விற்கவும் ↑",
    mustard: "கடுகு",
    hold1Week: "1 வாரம் காத்திருக்கவும்",
    paddy: "நெல்",
    priceFalling: "விலை குறைகிறது ↓",
    logout: "வெளியேறு",
    dashboard: "டாஷ்போர்டு",
    droneUpload: "ட்ரோன் பதிவேற்றம்",
    profit: "இலாபம்",
    scanGeneralTip: "பருவத்தின் 2-3 முக்கியமான கட்டங்களில் மட்டுமே உயர்-மதிப்பு ட்ரோன் ஸ்கேன்களை நடத்துங்கள்; ஒவ்வொரு வாரமும் ட்ரோன் பறக்க வேண்டிய அவசியமில்லை.",
    scanRecommendedPrefix: "இந்த வாரம் ஸ்கேன் பரிந்துரைக்கப்படுகிறது ",
    scanRecommendedSuffix: " (முக்கிய வளர்ச்சி நிலை).",
    scansThisSeason: "{{done}}/{{total}} இந்த பருவத்தில் ஸ்கேன்கள்",
    scanDueNow: "இப்போது ஸ்கேன் செய்ய வேண்டும் ({{stage}} நிலை)",
    nextScanInDays: "அடுத்த ஸ்கேன்: {{stage}} ~{{days}} நாட்களில்",
    dashboardTitle: "விவசாயி ட்ரோன் டாஷ்போர்டு",
    farmerDroneDashboard: "விவசாயி ட்ரோன் டாஷ்போர்ட்",
    mainSathi: "மெயின் சதி — உங்கள் பார்மிங் அசிஸ்டன்ட்",
    cropHealth: "பயிர் ஆரோக்கியம் & பூச்சி பிரச்சனைகள்",
    droneScan: "ட்ரோன் ஸ்கேன் அறிக்கைகள்",
    useApp: "ஆப் பயன்படுத்தவும்",
    selectLang: "மொழி தேர்ந்தெடுக்கவும் — ஹிந்தி, ஆங்கிலம் அல்லது மற்றவை",
    profitCalculatorTitle: "பயிர் லாப கணிப்பான்",
    profitCalculatorDesc: "உங்கள் பயிருக்கான விளைச்சல், வருவாய் மற்றும் லாபத்தை மதிப்பிடுங்கள்.",
    uploadDroneTitle: "ட்ரோன் படங்களைப் பதிவேற்றவும்",
    uploadDroneDesc: "பூச்சி, அழுத்தம் மற்றும் விளைச்சல் பகுப்பாய்விற்கு வயல் படங்களை AI-க்கு அனுப்பவும்.",
    aiAssistantTitle: "AI பண்ணை உதவியாளர்",
    chatWelcome: "வணக்கம்! உங்கள் பயிர், விளைச்சல் அல்லது விலைகள் பற்றி என்னிடம் கேளுங்கள்.",
    chatDemoReply: "டெமோ பதில்: நான் உங்கள் வயல் மற்றும் விலைகளை பகுப்பாய்வு செய்வேன்.",
    chatPlaceholder: "உங்கள் கேள்வியை ஆங்கிலம்/தமிழில் தட்டச்சு செய்யவும்...",
    send: "அனுப்பு",
    askSathi: "சாத்தியிடம் கேளுங்கள்",
    forgotPasswordTitle: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    forgotPasswordDesc: "உங்கள் AgriVistaar கணக்கிற்கு புதிய கடவுச்சொல்லை உருவாக்கவும்.",
    saveNewPassword: "புதிய கடவுச்சொல்லைச் சேமிக்கவும்",
    requestScanButton: "ட்ரோன் ஸ்கேன் கோரவும்",
    viewLastScanButton: "கடைசி ஸ்கேன் அறிக்கையைக் காண்க",
    dropImageHere: "ட்ரோன் படத்தை இங்கே விடுங்கள்",
dropImageOr: "அல்லது",
browseLink: "உலாவு",
dropImageToSelect: "செய்து தேர்ந்தெடுக்கவும்",
supportedFormats: "ஆதரிக்கப்படுகிறது: JPG, PNG, WEBP",
orDivider: "அல்லது",
chooseFileButton: "கோப்பை தேர்ந்தெடு",
analyzingStatus: "பகுப்பாய்வு நடக்கிறது...",
analysisResultTitle: "பகுப்பாய்வு முடிவு",
removeFile: "நீக்கு",
resCropHealth: "பயிர் ஆரோக்கியம்",
resRiskLevel: "ஆபத்து நிலை",
resNdvi: "NDVI ஸ்கோர்",
resAffectedArea: "பாதிக்கப்பட்ட பகுதி",
resRecommendation: "பரிந்துரை",
resDiseases: "கண்டறியப்பட்ட நோய்கள்",
resAnomalies: "முரண்பாடுகள்",
infoCropHealth: "பயிர் ஆரோக்கியம்",
infoCropHealthDesc: "NDVI பகுப்பாய்வு",
infoPestDetection: "பூச்சி கண்டறிதல்",
infoPestDetectionDesc: "AI ஸ்கேன்",
infoMoisture: "ஈரப்பத வரைபடம்",
infoMoistureDesc: "அழுத்த மண்டலங்கள்",
    areaPlaceholder: "பரப்பளவு (ஏக்கர்)",
    totalCostPlaceholder: "மொத்த செலவு (₹)",
    expectedPricePlaceholder: "எதிர்பார்க்கப்படும் சந்தை விலை (₹ ஒரு குவிண்டாலுக்கு)",
    predictedYieldPlaceholder: "மதிப்பிடப்பட்ட விளைச்சல் (குவிண்டால் ஒரு ஏக்கருக்கு)",
    analyzeFieldButton: "வயலை பகுப்பாய்வு செய்யவும்",
    requestScanTitle: "ட்ரோன் ஸ்கேன் கோரவும்",
    requestScanDesc: "எந்த வயல் மற்றும் பயிர் நிலையை ஸ்கேன் செய்ய வேண்டும் என்பதைத் தேர்ந்தெடுக்கவும். இந்த கோரிக்கை உங்கள் FPO / ட்ரோன் ஆபரேட்டருக்கு செல்லும்.",
    fieldLabel: "வயல்",
    cropStageLabel: "பயிர் நிலை",
    preferredDateLabel: "விரும்பிய தேதி",
    pilotNotesLabel: "பைலட்டுக்கான குறிப்புகள் (விருப்பமானது)",
    submitScanButton: "ஸ்கேன் கோரிக்கையை சமர்ப்பிக்கவும்",
    lastScanTitle: "கடைசி ட்ரோன் ஸ்கேன் அறிக்கை",
    lastScanDesc: "உங்கள் வயல்களுக்கான சமீபத்திய ட்ரோன் படங்கள், பூச்சி ஆபத்து, ஊட்டச்சத்து அழுத்தம் மற்றும் விளைச்சல் மதிப்பீட்டைக் காண்க.",
    healthSummaryTitle: "ஆரோக்கிய சுருக்கம்",
    yieldPredictionTitle: "விளைச்சல் கணிப்பு",
    pestRiskMedium: "பூச்சி ஆபத்து: நடுத்தரம் (வடபுறத்தில் திட்டுகள்)",
    nutrientStressLow: "ஊட்டச்சத்து அழுத்தம்: குறைவு",
    expectedYieldLine: "எதிர்பார்க்கப்படும் விளைச்சல்: 22–26 குவிண்டால்/ஏக்கர்",
    profitHint: "இந்த விளைச்சலுக்கான எதிர்பார்க்கப்படும் வருமானம் மற்றும் லாபத்தைப் பார்க்க இலாப கணிப்பான் பக்கத்தைப் பயன்படுத்தவும்.",
    dronePlaceholder: "ட்ரோன் படம் / NDVI வரைபட ஸ்தான",
    homeTitle: "உங்கள் வயல்கள்",
    selectFieldPlaceholder: "வயலைத் தேர்ந்தெடுக்கவும்",
    stageLabel: "வளர்ச்சி நிலை",
    selectStagePlaceholder: "நிலையைத் தேர்ந்தெடுக்கவும்",
    stageEarly: "ஆரம்ப தாவர நிலை",
    stageMid: "மத்திய பருவம்",
    stagePreHarvest: "அறுவடைக்கு முன்",
    dateLabel: "விரும்பிய ஸ்கேன் தேதி",
    notesLabel: "FPO-க்கான குறிப்புகள் (விருப்பமானது)",
    notesPlaceholder: "எ.கா. வடபுறத்தில் உள்ள மஞ்சள் திட்டுகளில் கவனம் செலுத்தவும்",
    submitScanRequest: "கோரிக்கையை சமர்ப்பிக்கவும்",
    fieldRequired: "வயல் தேவை",
    stageRequired: "நிலை தேவை",
    dateRequired: "விரும்பிய தேதி தேவை",
    fieldHealthy: "ஆரோக்கியமான பயிர்",
    fieldDetailTitlePrefix: "வயல் #",
    fieldDetailTitleSuffix: "– ஆரோக்கியம் & விளைச்சல்",
    openProfitCalculator: "இலாப கணிப்பானைத் திறக்கவும்",
    myFieldsTitle: "என் நிலங்கள்",
    myFieldsHelp: "அந்த நிலத்தின் ஸ்கான் நிலை மற்றும் விவரங்கள் பார்க்க நிலத்தைத் தொட்டு திறக்கவும்.",
    noFields: "இன்னும் எந்த நிலமும் சேர்க்கப்படவில்லை.",
    fieldCrop: "பயிர்:",
    lastScanLabel: "கடைசி ஸ்கான்:",
    notScanned: "இன்னும் ஸ்கான் செய்யப்படவில்லை",
    myScansTitle: "என் ட்ரோன் ஸ்கான்கள்",
    myScansHelp: "சமீபத்திய அனைத்து ட்ரோன் ஸ்கான்களின் பட்டியல். முழு அறிக்கை பார்க்க எந்த வரியையும் தொட்டு திறக்கவும்.",
    noScans: "இன்னும் எந்த ஸ்கானும் இல்லை.",
    fieldFallback: "நிலம்",
    analysisPendingShort: "ஆய்வு நடைபெற்று வருகிறது",
    lastScanField: "வயல்:",
    lastScanStatus: "நிலை:",
    lastScanDate: "தேதி:",
    lastScanAnalysis: "மொத்தப் பரப்பளவில் சுமார் 18% இடத்தில் லேசான அழுத்தம் கண்டறியப்பட்டது, பெரும்பாலும் வடபக்கத்தில். 3 நாட்களுக்குள் நைட்ரஜன் தெளிப்பு செய்ய பரிந்துரைக்கப்படுகிறது.",
    analysisPendingLong: "ஆய்வு நடைபெற்று வருகிறது. படங்களை பதிவேற்றி செயல்படுத்திய பிறகு அறிக்கை தயார் செய்யப்படும்.",
    tapToViewReport: "முழு அறிக்கையைப் பார்க்க தொட்டு திறக்கவும்",
    requested: "ஸ்கான் கோரப்பட்டது",
    imagesUploaded: "ஆய்வு நடைபெற்று வருகிறது",
    completed: "அறிக்கை தயார்",
    unknownStatus: "நிலை தெரியவில்லை",
    healthyCropLabel: "பயிர் நிலை: நலமாக உள்ளது",
    cropLabel: "பயிர்:",
    sowingDateLabel: "விதைத்த தேதி:",
    fieldNotFound: "நிலம் கிடைக்கவில்லை.",
    myScans: "என் ஸ்கான்கள்",
    lastScan: "கடைசி ஸ்கான்",
    calculateButton: "பயிர் லாப கணிப்பான்",
    allFieldsRequired: "அனைத்து தகவல்களையும் நிரப்பவும்.",
    positiveValuesRequired: "அனைத்து மதிப்புகளும் 0-ஐ விட அதிகமாக இருக்க வேண்டும்.",
    totalYieldLabel: "மொத்த விளைச்சல்",
    totalRevenueLabel: "மொத்த வருமானம்",
    totalCostLabel: "மொத்த செலவு",
    netProfitLabel: "நிகர லாபம்",
    quintalUnit: "குவிண்டால்",
    profitCalculatorHint: "எதிர்பார்க்கப்படும் சந்தை விலையின் அடிப்படையில் மதிப்பீடு. உண்மையான முடிவுகள் மாறுபடலாம்.",
    analysisCompleteMessage: "வயல் பகுப்பாய்வு முடிந்தது! முடிவுகளுக்கு உங்கள் டாஷ்போர்டைப் பார்க்கவும்.",
    scanItemCompleted: "நிறைவு செய்யப்பட்டது",
    scanItemRequested: "கோரப்பட்டது",
    criticalScanTip: "முக்கியமான நிலைகளில் ஸ்கேன்களைச் செய்யுங்கள்: ஆரம்பத்தில், நடு-பயிர் நிலையில், அறுவடைக்கு முன்.",
  },

  bn: {
    appName: "AgriVistaar",
    tagline: "কৃষকের সাথী",
    precisionAg: "নির্ভুল কৃষি • ড্রোন বিশ্লেষণ",
    login: "লগইন",
    signup: "সাইন আপ",
    welcome: "নমস্কার, কৃষক ভাই 👋",
    welcomeFarmer: "নমস্কার, কৃষক ভাই",
    requiredField: "প্রয়োজনীয়",
    passwordMismatch: "পাসওয়ার্ড মিলছে না",
    wrongPassword: "ভুল পাসওয়ার্ড",
    userNotFound: "ব্যবহারকারী পাওয়া যায়নি",
    userAlreadyExists: "ব্যবহারকারী ইতিমধ্যে বিদ্যমান",
    signupFailed: "সাইন আপ ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    loginFailed: "লগইন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    newFieldName: "নতুন প্লট",
    loadError: "ড্যাশবোর্ড লোড করা যায়নি",
    loading: "লোড হচ্ছে...",
    scanSubmitError: "স্ক্যান অনুরোধ ব্যর্থ হয়েছে। আবার চেষ্টা করুন।",
    getStarted: "শুরু করুন",
    createAccount: "বিনামূল্যে অ্যাকাউন্ট তৈরি করুন",
    heroText: "আকাশ থেকে কীটপতঙ্গ, পুষ্টি চাপ এবং ফলন দেখুন, এবং সর্বোচ্চ লাভের জন্য আপনার ফসল বিক্রি করার সেরা সময় এবং মান্ডি জানুন।",
    droneInsights: "ড্রোন অন্তর্দৃষ্টি",
    droneInsightsDesc: "কীটপতঙ্গ এবং চাপ তাড়াতাড়ি সনাক্ত করুন",
    mandiTiming: "স্মার্ট মান্ডি সময়",
    mandiTimingDesc: "যখন দাম সবচেয়ে বেশি তখন বিক্রি করুন",
    yieldPrediction: "ফলন পূর্বাভাস",
    yieldPredictionDesc: "নিখুঁতভাবে ফসল কাটার পরিকল্পনা করুন",
    farmers: "কৃষক",
    acresMonitored: "একর পর্যবেক্ষণ করা হয়েছে",
    accuracy: "নির্ভুলতা",
    aiSupport: "AI সহায়তা",
    liveMonitoring: "লাইভ পর্যবেক্ষণ",
    updatedAgo: "২ ঘন্টা আগে আপডেট করা হয়েছে",
    droneView: "ফসলের ক্ষেতের ড্রোন দৃশ্য",
    aiPowered: "(AI-চালিত বিশ্লেষণ)",
    pestRisk: "কীট ঝুঁকি",
    nutrient: "পুষ্টি",
    yield: "ফলন",
    low: "কম",
    onArea: "৮০% এলাকায়",
    mediumN: "মাঝারি N",
    stressNorth: "উত্তরে চাপ",
    perAcre: "প্রতি একর",
    myFields: "আমার জমি",
    clickField: "ড্রোনের হেলথ ম্যাপ এবং ফলন দেখতে কোনো জমির কার্ডে ট্যাপ করুন।",
    myScans: "আমার স্ক্যান",
    lastScan: "সর্বশেষ স্ক্যান",
    farmerDroneDashboard: "কৃষক ড্রোন ড্যাশবোর্ড",
    myFieldsTitle: "আমার জমি",
    myFieldsHelp: "জমির স্ক্যান স্টেটাস ও বিস্তারিত দেখতে জমির উপর ট্যাপ করুন।",
    noFields: "এখনো কোনো জমি যোগ করা হয়নি।",
    fieldCrop: "ফসল:",
    lastScanLabel: "সর্বশেষ স্ক্যান:",
    notScanned: "এখনো স্ক্যান করা হয়নি",
    myScansTitle: "আমার ড্রোন স্ক্যান",
    myScansHelp: "আপনার সাম্প্রতিক সব ড্রোন স্ক্যানের তালিকা। সম্পূর্ণ রিপোর্ট দেখতে যে কোনো লাইন ট্যাপ করুন।",
    noScans: "এখনো কোনো স্ক্যান নেই।",
    fieldFallback: "জমি",
    analysisPendingShort: "বিশ্লেষণ চলছে",
    lastScanTitle: "সর্বশেষ স্ক্যান",
    lastScanField: "জমি:",
    lastScanStatus: "অবস্থা:",
    lastScanDate: "তারিখ:",
    analysisPendingLong: "বিশ্লেষণ চলছে। ছবি আপলোড ও প্রসেসিং শেষ হলে রিপোর্ট প্রস্তুত হবে।",
    tapToViewReport: "সম্পূর্ণ রিপোর্ট দেখতে ট্যাপ করুন",
    requested: "স্ক্যানের অনুরোধ করা হয়েছে",
    imagesUploaded: "বিশ্লেষণ প্রক্রিয়াধীন",
    completed: "রিপোর্ট প্রস্তুত",
    unknownStatus: "অবস্থা অজানা",
    healthyCropLabel: "ফসলের অবস্থা: সুস্থ",
    cropLabel: "ফসল:",
    sowingDateLabel: "বপনের তারিখ:",
    requestScanButton: "ড্রোন স্ক্যানের অনুরোধ করুন",
    fieldNotFound: "জমি পাওয়া যায়নি।",
    requestScanTitle: "ড্রোন স্ক্যানের অনুরোধ করুন",
    requestScanDesc: "কোন ক্ষেত এবং ফসলের পর্যায় স্ক্যান করতে চান তা নির্বাচন করুন। এই অনুরোধ আপনার FPO / ড্রোন অপারেটরের কাছে যাবে।",
    fieldLabel: "ক্ষেত",
    selectFieldPlaceholder: "জমির নাম বা আইডি লিখুন / নিশ্চিত করুন",
    fieldRequired: "দয়া করে জমির নাম বা আইডি লিখুন।",
    stageLabel: "ফসলের ধাপ",
    cropStageLabel: "ফসলের পর্যায়",
    selectStagePlaceholder: "ফসলের ধাপ নির্বাচন করুন",
    stageEarly: "প্রারম্ভিক বৃদ্ধি",
    stageMid: "মধ্য পর্যায়",
    stagePreHarvest: "কাটাইয়ের আগে",
    stageRequired: "দয়া করে ফসলের ধাপ নির্বাচন করুন।",
    dateLabel: "প্রিয় স্ক্যানের তারিখ",
    dateRequired: "দয়া করে একটি তারিখ নির্বাচন করুন।",
    preferredDateLabel: "পছন্দের তারিখ",
    notesLabel: "ড্রোন পাইলটের জন্য নোট",
    notesPlaceholder: "কোনো দৃশ্যমান সমস্যা বা নির্দেশ থাকলে লিখুন (ঐচ্ছিক)।",
    pilotNotesLabel: "পাইলটের জন্য নোট (ঐচ্ছিক)",
    scanRequestSuccess: "আপনার ড্রোন স্ক্যানের অনুরোধ পাঠানো হয়েছে।",
    submitScanRequest: "স্ক্যান অনুরোধ সাবমিট করুন",
    submitScanButton: "স্ক্যান অনুরোধ জমা দিন",
    loginTo: "লগইন করুন",
    phone: "ফোন নম্বর / ইমেইল",
    dropImageHere: "এখানে ড্রোন ছবি ছেড়ে দিন",
dropImageOr: "অথবা",
browseLink: "ব্রাউজ করুন",
dropImageToSelect: "করে বেছে নিন",
supportedFormats: "সমর্থিত: JPG, PNG, WEBP",
orDivider: "অথবা",
chooseFileButton: "ফাইল বেছে নিন",
analyzingStatus: "বিশ্লেষণ চলছে...",
analysisResultTitle: "বিশ্লেষণের ফলাফল",
removeFile: "সরান",
infoCropHealth: "ফসলের স্বাস্থ্য",
infoCropHealthDesc: "NDVI বিশ্লেষণ",
infoPestDetection: "কীট সনাক্তকরণ",
infoPestDetectionDesc: "AI স্ক্যান",
infoMoisture: "আর্দ্রতার মানচিত্র",
infoMoistureDesc: "চাপ অঞ্চল",
    phonePlaceholder: "ফোন নম্বর বা ইমেইল লিখুন",
    password: "পাসওয়ার্ড / OTP",
    passwordPlaceholder: "••••••",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    support: "সহায়তা: 1800-XXX-XXXX",
    newTo: "নতুন",
    loginDesc: "আপনার খামারের জন্য উপযুক্ত ড্রোন স্ক্যান, ফসলের স্বাস্থ্য এবং মান্ডি সংকেত দেখতে আপনার নিবন্ধিত ফোন বা ইমেইল ব্যবহার করুন।",
    join: "যোগ দিন",
    newFarmerAccount: "নতুন কৃষক অ্যাকাউন্ট",
    signupDesc: "আপনার ক্ষেতের জন্য AI-চালিত কীট সতর্কতা, পুষ্টি চাপ মানচিত্র এবং মান্ডি সময় পরামর্শ পান।",
    name: "নাম",
    namePlaceholder: "কৃষকের নাম",
    phoneNumber: "ফোন নম্বর / ইমেইল",
    phoneDesc: "OTP, লগইন এবং ফসল সতর্কতার জন্য",
    district: "জেলা",
    districtPlaceholder: "যেমন সীতাপুর",
    state: "রাজ্য",
    statePlaceholder: "উত্তরপ্রদেশ",
    passwordLabel: "পাসওয়ার্ড",
    passwordSignupPlaceholder: "একটি শক্তিশালী পাসওয়ার্ড চয়ন করুন",
    createAccountBtn: "অ্যাকাউন্ট তৈরি করুন",
    agreeText: "সাইন আপ করে আপনি আপনার মোবাইল নম্বর বা ইমেইলে গুরুত্বপূর্ণ ফসল সতর্কতা পেতে সম্মত হচ্ছেন।",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    confirmPasswordLabel: "পাসওয়ার্ড নিশ্চিত করুন",
    confirmPasswordPlaceholder: "পাসওয়ার্ড পুনরায় লিখুন",
    mainSathi: "মেইন সাথী — আপনার ফার্মিং অ্যাসিস্টেন্ট",
    cropHealth: "ফসলের স্বাস্থ্য ও পোকার সমস্যা",
    droneScan: "ড্রোন স্ক্যান রিপোর্ট",
    useApp: "অ্যাপ ব্যবহার করুন",
    selectLang: "ভাষা নির্বাচন করুন — হিন্দি, ইংরেজি বা অন্যান্য",
    todaySnapshot: "এখানে আপনার ক্ষেত, স্বাস্থ্য এবং আয়ের আজকের স্ন্যাপশট।",
    droneUpdated: "ড্রোন স্ক্যান ২ ঘন্টা আগে আপডেট করা হয়েছে • আবহাওয়া: স্প্রে করার জন্য ভাল",
    totalFields: "মোট ক্ষেত",
    atRiskFields: "ঝুঁকিপূর্ণ ক্ষেত",
    avgYield: "গড় ফলন (কুইন্টাল/একর)",
    expectedIncome: "প্রত্যাশিত আয় (₹)",
    addNewField: "নতুন ক্ষেত যোগ করুন",
    wheatNorth: "উত্তরের গমের ক্ষেত",
    moderatePestRisk: "মাঝারি কীট ঝুঁকি",
    mustardEast: "সরিষা – পূর্ব প্লট",
    healthy: "সুস্থ",
    paddySouth: "নিচু জমির ধান",
    nutrientStress: "পুষ্টি চাপ",
    todayMandi: "আজকের মান্ডি সংকেত",
    mandiDesc: "গত ৩০ দিনের মান্ডি ডেটা এবং পূর্বাভাসিত দামের উপর ভিত্তি করে।",
    wheat: "গম",
    sellNow: "এখন বিক্রি করুন ↑",
    mustard: "সরিষা",
    hold1Week: "১ সপ্তাহ ধরে রাখুন",
    paddy: "ধান",
    priceFalling: "দাম কমছে ↓",
    logout: "লগ আউট",
    dashboard: "ড্যাশবোর্ড",
    droneUpload: "ড্রোন আপলোড",
    profit: "লাভ",
    scanGeneralTip: "মৌসুমের ২-৩টি গুরুত্বপূর্ণ পর্যায়ে শুধুমাত্র উচ্চ-মূল্যের ড্রোন স্ক্যান পরিচালনা করুন; প্রতি সপ্তাহে ড্রোন উড়ানোর প্রয়োজন নেই।",
    scanRecommendedPrefix: "এই সপ্তাহে স্ক্যানের সুপারিশ করা হয়েছে ",
    scanRecommendedSuffix: " (মূল বৃদ্ধির পর্যায়)।",
    scansThisSeason: "{{done}}/{{total}} এই মৌসুমে স্ক্যান",
    scanDueNow: "এখন স্ক্যান করা দরকার ({{stage}} পর্যায়)",
    nextScanInDays: "পরবর্তী স্ক্যান: {{stage}} ~{{days}} দিনে",
    dashboardTitle: "কৃষক ড্রোন ড্যাশবোর্ড",
    lastScanAnalysis: "মোটামুটি ১৮% এলাকায় হালকা চাপ শনাক্ত হয়েছে, মূলত উত্তর দিকে। ৩ দিনের মধ্যে নাইট্রোজেন স্প্রে করার সুপারিশ করা হচ্ছে।",
    scanItemCompleted: "সম্পূর্ণ",
    scanItemRequested: "অনুরোধ করা হয়েছে",
    profitCalculatorTitle: "ফসল লাভ ক্যালকুলেটর",
    profitCalculatorDesc: "আপনার ফসলের ফলন, রাজস্ব এবং লাভ অনুমান করুন।",
    uploadDroneTitle: "ড্রোন ছবি আপলোড করুন",
    uploadDroneDesc: "কীট, চাপ এবং ফলন বিশ্লেষণের জন্য AI-তে ক্ষেতের ছবি পাঠান।",
    aiAssistantTitle: "AI খামার সহায়ক",
    chatWelcome: "নমস্কার! আপনার ফসল, ফলন বা দাম সম্পর্কে আমাকে জিজ্ঞাসা করুন।",
    chatDemoReply: "ডেমো উত্তর: আমি আপনার ক্ষেত এবং দাম বিশ্লেষণ করব।",
    chatPlaceholder: "আপনার প্রশ্ন ইংরেজি/বাংলায় টাইপ করুন...",
    send: "পাঠান",
    askSathi: "সাথীকে জিজ্ঞাসা করুন",
    forgotPasswordTitle: "পাসওয়ার্ড ভুলে গেছেন?",
    forgotPasswordDesc: "আপনার AgriVistaar অ্যাকাউন্টের জন্য একটি নতুন পাসওয়ার্ড তৈরি করুন।",
    saveNewPassword: "নতুন পাসওয়ার্ড সংরক্ষণ করুন",
    viewLastScanButton: "শেষ স্ক্যান রিপোর্ট দেখুন",
    areaPlaceholder: "এলাকা (একর)",
    totalCostPlaceholder: "মোট খরচ (₹)",
    expectedPricePlaceholder: "প্রত্যাশিত বাজার মূল্য (₹ প্রতি কুইন্টাল)",
    predictedYieldPlaceholder: "পূর্বাভাসিত ফলন (কুইন্টাল প্রতি একর)",
    analyzeFieldButton: "ক্ষেত বিশ্লেষণ করুন",
    lastScanDesc: "আপনার ক্ষেতের জন্য সর্বশেষ ড্রোন ছবি, কীট ঝুঁকি, পুষ্টি চাপ এবং ফলন অনুমান দেখুন।",
    healthSummaryTitle: "স্বাস্থ্য সারসংক্ষেপ",
    yieldPredictionTitle: "ফলন পূর্বাভাস",
    pestRiskMedium: "কীট ঝুঁকি: মাঝারি (উত্তর দিকে প্যাচ)",
    nutrientStressLow: "পুষ্টি চাপ: কম",
    expectedYieldLine: "প্রত্যাশিত ফলন: ২২–২৬ কুইন্টাল/একর",
    profitHint: "এই ফলনের জন্য প্রত্যাশিত আয় এবং লাভ দেখতে লাভ ক্যালকুলেটর পৃষ্ঠা ব্যবহার করুন।",
    dronePlaceholder: "ড্রোন ছবি / NDVI মানচিত্র প্লেসহোল্ডার",
    homeTitle: "আপনার ক্ষেত",
    fieldHealthy: "সুস্থ ফসল",
    fieldDetailTitlePrefix: "ক্ষেত #",
    fieldDetailTitleSuffix: "– স্বাস্থ্য এবং ফলন",
    openProfitCalculator: "লাভ ক্যালকুলেটর খুলুন",
    calculateButton: "ফসলের লাভ ক্যালকুলেটর",
    allFieldsRequired: "অনুগ্রহ করে সব ঘর পূরণ করুন।",
    positiveValuesRequired: "সব মান ০-এর বেশি হতে হবে।",
    totalYieldLabel: "মোট ফলন",
    totalRevenueLabel: "মোট আয়",
    totalCostLabel: "মোট খরচ",
    netProfitLabel: "নিট লাভ",
    quintalUnit: "কুইন্টাল",
    profitCalculatorHint: "প্রত্যাশিত বাজার মূল্যের উপর ভিত্তি করে অনুমান। প্রকৃত ফলাফল আলাদা হতে পারে।",
    analysisCompleteMessage: "মাঠ বিশ্লেষণ সম্পন্ন! ফলাফলের জন্য আপনার ড্যাশবোর্ড দেখুন।",
    criticalScanTip: "গুরুত্বপূর্ণ পর্যায়ে স্ক্যান করুন: শুরুতে, মধ্য-ফসলের পর্যায়ে এবং ফসল কাটার আগে.",
  },

  te: {
    appName: "AgriVistaar",
    tagline: "రైతు స్నేహితుడు",
    precisionAg: "ఖచ్చితమైన వ్యవసాయం • డ్రోన్ విశ్లేషణ",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    welcome: "నమస్కారం, రైతు గారు 👋",
    welcomeFarmer: "నమస్కారం, రైతు గారు",
    requiredField: "అవసరం",
    passwordMismatch: "పాస్‌వర్డ్‌లు సరిపోలడం లేదు",
    wrongPassword: "తప్పు పాస్‌వర్డ్",
    userNotFound: "వినియోగదారుడు కనుగొనబడలేదు",
    userAlreadyExists: "వినియోగదారుడు ఇప్పటికే ఉన్నారు",
    signupFailed: "సైన్ అప్ విఫలమైంది. మళ్లీ ప్రయత్నించండి.",
    loginFailed: "లాగిన్ విఫలమైంది. మళ్లీ ప్రయత్నించండి.",
    loadError: "డాష్‌బోర్డ్ లోడ్ కాలేదు",
    loading: "లోడ్ అవుతోంది...",
    scanSubmitError: "స్కాన్ అభ్యర్థన విఫలమైంది. మళ్లీ ప్రయత్నించండి.",
    getStarted: "ప్రారంభించండి",
    createAccount: "ఉచిత ఖాతాను సృష్టించండి",
    heroText: "ఆకాశం నుండి పురుగులు, పోషక ఒత్తిడి మరియు దిగుబడిని చూడండి, మరియు గరిష్ట లాభం కోసం మీ పంటను అమ్మడానికి ఉత్తమ సమయం మరియు మార్కెట్‌ను తెలుసుకోండి.",
    droneInsights: "డ్రోన్ అంతర్దృష్టులు",
    droneInsightsDesc: "పురుగులు & ఒత్తిడిని ముందుగానే గుర్తించండి",
    mandiTiming: "స్మార్ట్ మార్కెట్ సమయం",
    mandiTimingDesc: "ధరలు అత్యధికంగా ఉన్నప్పుడు అమ్మండి",
    yieldPrediction: "దిగుబడి అంచనా",
    yieldPredictionDesc: "కోతను ఖచ్చితంగా ప్లాన్ చేయండి",
    farmers: "రైతులు",
    acresMonitored: "ఎకరాలు పర్యవేక్షించబడ్డాయి",
    accuracy: "ఖచ్చితత్వం",
    aiSupport: "AI మద్దతు",
    liveMonitoring: "లైవ్ పర్యవేక్షణ",
    updatedAgo: "2 గంటల క్రితం నవీకరించబడింది",
    droneView: "పంట పొలం యొక్క డ్రోన్ వీక్షణ",
    aiPowered: "(AI-శక్తితో విశ్లేషణ)",
    pestRisk: "పురుగుల ప్రమాదం",
    nutrient: "పోషకం",
    yield: "దిగుబడి",
    low: "తక్కువ",
    onArea: "80% ప్రాంతంలో",
    mediumN: "మధ్యస్థ N",
    stressNorth: "ఉత్తరాన ఒత్తిడి",
    perAcre: "ఎకరుకు",
    myFields: "నా పొలాలు",
    clickField: "డ్రోన్ హెల్త్ మ్యాప్ మరియు దిగుబడి చూడటానికి పొలం కార్డ్‌పై ట్యాప్ చేయండి.",
    myScans: "నా స్కాన్‌లు",
    lastScan: "చివరి స్కాన్",
    farmerDroneDashboard: "రైతు డ్రోన్ డాష్‌బోర్డ్",
    myFieldsTitle: "నా పొలాలు",
    myFieldsHelp: "ఆ పొలం యొక్క స్కాన్ స్థితి మరియు వివరాలు చూడటానికి పొలంపై ట్యాప్ చేయండి.",
    noFields: "ఇప్పటికీ ఏ పొలం నమోదు కాలేదు.",
    fieldCrop: "పంట:",
    lastScanLabel: "చివరి స్కాన్:",
    notScanned: "ఇంకా స్కాన్ చేయలేదు",
    myScansTitle: "నా డ్రోన్ స్కాన్‌లు",
    myScansHelp: "మీ తాజా డ్రోన్ స్కాన్‌ల చరిత్ర. పూర్తి రిపోర్ట్ కోసం ఏ లైన్‌పైనైనా ట్యాప్ చేయండి.",
    noScans: "ఇప్పటికీ ఎలాంటి స్కాన్ లేదు.",
    fieldFallback: "పొలం",
    analysisPendingShort: "విశ్లేషణ కొనసాగుతోంది",
    lastScanTitle: "చివరి స్కాన్",
    lastScanField: "పొలం:",
    lastScanStatus: "స్థితి:",
    lastScanDate: "తేదీ:",
    analysisPendingLong: "విశ్లేషణ కొనసాగుతోంది. చిత్రాలు అప్‌లోడ్ అయ్యి ప్రాసెస్ అయిన తరువాత రిపోర్ట్ సిద్ధమవుతుంది.",
    tapToViewReport: "పూర్తి రిపోర్ట్ కోసం ట్యాప్ చేయండి",
    requested: "స్కాన్ అభ్యర్థించబడింది",
    imagesUploaded: "విశ్లేషణ జరుగుతోంది",
    completed: "రిపోర్ట్ సిద్ధం",
    unknownStatus: "స్థితి తెలియదు",
    healthyCropLabel: "పంట స్థితి: ఆరోగ్యంగా ఉంది",
    cropLabel: "పంట:",
    sowingDateLabel: "విత్తిన తేదీ:",
    requestScanButton: "డ్రోన్ స్కాన్ కోరండి",
    fieldNotFound: "పొలం కనపడలేదు.",
    requestScanTitle: "డ్రోన్ స్కాన్ అభ్యర్థన",
    requestScanDesc: "ఏ పొలం మరియు పంట దశను స్కాన్ చేయాలో ఎంచుకోండి. ఈ అభ్యర్థన మీ FPO / డ్రోన్ ఆపరేటర్‌కు వెళుతుంది.",
    fieldLabel: "పొలం",
    selectFieldPlaceholder: "పొలం పేరు / ఐడి నమోదు చేయండి లేదా ధృవీకరించండి",
    fieldRequired: "దయచేసి పొలం పేరు లేదా ఐడి నమోదు చేయండి.",
    stageLabel: "పంట దశ",
    cropStageLabel: "పంట దశ",
    selectStagePlaceholder: "పంట దశను ఎంచుకోండి",
    stageEarly: "ఆరంభ దశ",
    stageMid: "మధ్య దశ",
    stagePreHarvest: "పంట కోతకు ముందు",
    stageRequired: "దయచేసి ఒక దశను ఎంచుకోండి.",
    dateLabel: "ఇష్టమైన స్కాన్ తేదీ",
    dateRequired: "దయచేసి తేదీని ఎంచుకోండి.",
    preferredDateLabel: "ప్రాధాన్యత తేదీ",
    notesLabel: "డ్రోన్ పైలట్‌కి నోట్లు",
    notesPlaceholder: "కనిపించే సమస్యలు లేదా సూచనలు ఉంటే రాయండి (ఐచ్చికం).",
    pilotNotesLabel: "పైలట్ కోసం గమనికలు (ఐచ్ఛికం)",
    scanRequestSuccess: "మీ డ్రోన్ స్కాన్ అభ్యర్థన సమర్పించబడింది.",
    submitScanRequest: "స్కాన్ అభ్యర్థన సమర్పించండి",
    submitScanButton: "స్కాన్ అభ్యర్థనను సమర్పించండి",
    loginTo: "లాగిన్ చేయండి",
    phone: "ఫోన్ నంబర్ / ఈమెయిల్",
    phonePlaceholder: "ఫోన్ నంబర్ లేదా ఈమెయిల్ నమోదు చేయండి",
    password: "పాస్‌వర్డ్ / OTP",
    passwordPlaceholder: "••••••",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    support: "మద్దతు: 1800-XXX-XXXX",
    newTo: "కొత్తవారా",
    loginDesc: "మీ పొలానికి అనుకూలమైన డ్రోన్ స్కాన్‌లు, పంట ఆరోగ్యం మరియు మార్కెట్ సంకేతాలను చూడటానికి మీ నమోదు చేసిన ఫోన్ లేదా ఈమెయిల్‌ను ఉపయోగించండి.",
    join: "చేరండి",
    dropImageHere: "డ్రోన్ చిత్రాన్ని ఇక్కడ వదలండి",
dropImageOr: "లేదా",
browseLink: "బ్రౌజ్ చేయండి",
dropImageToSelect: "చేసి ఎంచుకోండి",
supportedFormats: "మద్దతు: JPG, PNG, WEBP",
orDivider: "లేదా",
chooseFileButton: "ఫైల్ ఎంచుకోండి",
analyzingStatus: "విశ్లేషణ జరుగుతోంది...",
analysisResultTitle: "విశ్లేషణ ఫలితం",
removeFile: "తొలగించు",
infoCropHealth: "పంట ఆరోగ్యం",
infoCropHealthDesc: "NDVI విశ్లేషణ",
infoPestDetection: "పురుగుల గుర్తింపు",
infoPestDetectionDesc: "AI స్కాన్",
infoMoisture: "తేమ మ్యాప్",
infoMoistureDesc: "ఒత్తిడి మండలాలు",
    newFarmerAccount: "కొత్త రైతు ఖాతా",
    signupDesc: "మీ పొలాల కోసం AI-శక్తితో పురుగుల హెచ్చరికలు, పోషక ఒత్తిడి మ్యాప్‌లు మరియు మార్కెట్ సమయ సూచనలను పొందండి.",
    name: "పేరు",
    namePlaceholder: "రైతు పేరు",
    phoneNumber: "ఫోన్ నంబర్ / ఈమెయిల్",
    phoneDesc: "OTP, లాగిన్ మరియు పంట హెచ్చరికల కోసం",
    district: "జిల్లా",
    districtPlaceholder: "ఉదా. సీతాపూర్",
    state: "రాష్ట్రం",
    statePlaceholder: "ఉత్తరప్రదేశ్",
    passwordLabel: "పాస్‌వర్డ్",
    passwordSignupPlaceholder: "బలమైన పాస్‌వర్డ్‌ను ఎంచుకోండి",
    createAccountBtn: "ఖాతాను సృష్టించండి",
    agreeText: "సైన్ అప్ చేయడం ద్వారా మీరు మీ మొబైల్ నంబర్ లేదా ఈమెయిల్‌లో ముఖ్యమైన పంట హెచ్చరికలను స్వీకరించడానికి అంగీకరిస్తున్నారు.",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    confirmPasswordLabel: "పాస్‌వర్డ్‌ను నిర్ధారించండి",
    confirmPasswordPlaceholder: "పాస్‌వర్డ్‌ను మళ్లీ నమోదు చేయండి",
    todaySnapshot: "ఇక్కడ మీ పొలాలు, ఆరోగ్యం మరియు ఆదాయం యొక్క నేటి స్నాప్‌షాట్ ఉంది.",
    droneUpdated: "డ్రోన్ స్కాన్ 2 గంటల క్రితం నవీకరించబడింది • వాతావరణం: స్ప్రే చేయడానికి మంచిది",
    totalFields: "మొత్తం పొలాలు",
    atRiskFields: "ప్రమాదంలో ఉన్న పొలాలు",
    avgYield: "సగటు దిగుబడి (క్వింటాల్/ఎకరు)",
    expectedIncome: "ఆశించిన ఆదాయం (₹)",
    addNewField: "కొత్త పొలాన్ని జోడించండి",
    wheatNorth: "ఉత్తర గోధుమ పొలం",
    moderatePestRisk: "మధ్యస్థ పురుగుల ప్రమాదం",
    mustardEast: "ఆవాలు – తూర్పు ప్లాట్",
    healthy: "ఆరోగ్యకరమైనది",
    paddySouth: "తక్కువ భూమి వరి",
    nutrientStress: "పోషక ఒత్తిడి",
    todayMandi: "నేటి మార్కెట్ సంకేతం",
    mandiDesc: "గత 30 రోజుల మార్కెట్ డేటా మరియు అంచనా ధరల ఆధారంగా.",
    wheat: "గోధుమ",
    sellNow: "ఇప్పుడు అమ్మండి ↑",
    mustard: "ఆవాలు",
    hold1Week: "1 వారం పట్టుకోండి",
    paddy: "వరి",
    priceFalling: "ధర పడిపోతోంది ↓",
    logout: "లాగ్ అవుట్",
    dashboard: "డాష్‌బోర్డ్",
    droneUpload: "డ్రోన్ అప్‌లోడ్",
    profit: "లాభం",
    scanGeneralTip: "సీజన్‌లోని 2-3 క్లిష్టమైన దశల్లో మాత్రమే అధిక-విలువ డ్రోన్ స్కాన్‌లను నిర్వహించండి; ప్రతి వారం డ్రోన్‌ను ఎగురవేసే అవసరం లేదు.",
    scanRecommendedPrefix: "ఈ వారం స్కాన్ సిఫార్సు చేయబడింది ",
    scanRecommendedSuffix: " (కీలక పెరుగుదల దశ).",
    scansThisSeason: "{{done}}/{{total}} ఈ సీజన్‌లో స్కాన్‌లు",
    scanDueNow: "స్కాన్ ఇప్పుడు చేయాల్సి ఉంది ({{stage}} దశ)",
    nextScanInDays: "తదుపరి స్కాన్: {{stage}} ~{{days}} రోజుల్లో",
    dashboardTitle: "రైతు డ్రోన్ డాష్‌బోర్డ్",
    mainSathi: "ప్రధాన సహాయకుడు — మీరు ఫార్మింగ్ అసిస్టెంట్",
    cropHealth: "పంట ఆరోగ్యం & పెస్ట్ సమస్యలు",
    droneScan: "డ్రోన్ స్కాన్ రిపోర్టులు",
    useApp: "అప్ ఉపయోగించండి",
    selectLang: "భాష ఎంచుకోండి — హిందీ, ఇంగ్లీష్, లేదా ఇతరులు",
    calculateButton: "పంట లాభ కాలిక్యులేటర్",
    allFieldsRequired: "దయచేసి అన్ని వివరాలు నమోదు చేయండి.",
    positiveValuesRequired: "అన్ని విలువలు 0 కంటే ఎక్కువగా ఉండాలి.",
    totalYieldLabel: "మొత్తం దిగుబడి",
    totalRevenueLabel: "మొత్తం ఆదాయం",
    totalCostLabel: "మొత్తం ఖర్చు",
    netProfitLabel: "నికర లాభం",
    quintalUnit: "క్వింటాల్",
    profitCalculatorHint: "అంచనా వేయబడిన మార్కెట్ ధర ఆధారంగా లెక్కింపు. వాస్తవ ఫలితాలు మారవచ్చు.",
    analysisCompleteMessage: "పొలం విశ్లేషణ పూర్తయింది! ఫలితాల కోసం మీ డాష్‌బోర్డ్ చూడండి.",
    profitCalculatorTitle: "పంట లాభ కాలిక్యులేటర్",
    profitCalculatorDesc: "మీ పంట కోసం దిగుబడి, ఆదాయం మరియు లాభాన్ని అంచనా వేయండి.",
    uploadDroneTitle: "డ్రోన్ చిత్రాలను అప్‌లోడ్ చేయండి",
    uploadDroneDesc: "పురుగులు, ఒత్తిడి మరియు దిగుబడి విశ్లేషణ కోసం AI కి పొలం చిత్రాలను పంపండి.",
    aiAssistantTitle: "AI పొలం సహాయకుడు",
    chatWelcome: "నమస్కారం! మీ పంట, దిగుబడి లేదా ధరల గురించి నన్ను అడగండి.",
    chatDemoReply: "డెమో సమాధానం: నేను మీ పొలం మరియు ధరలను విశ్లేషిస్తాను.",
    chatPlaceholder: "మీ ప్రశ్నను ఇంగ్లీష్/తెలుగులో టైప్ చేయండి...",
    send: "పంపండి",
    askSathi: "సాథీని అడగండి",
    forgotPasswordTitle: "పాస్‌వర్డ్ మర్చిపోయారా?",
    forgotPasswordDesc: "మీ AgriVistaar ఖాతా కోసం కొత్త పాస్‌వర్డ్‌ను సృష్టించండి.",
    saveNewPassword: "కొత్త పాస్‌వర్డ్‌ను సేవ్ చేయండి",
    viewLastScanButton: "చివరి స్కాన్ నివేదికను చూడండి",
    areaPlaceholder: "విస్తీర్ణం (ఎకరు)",
    totalCostPlaceholder: "మొత్తం ఖర్చు (₹)",
    expectedPricePlaceholder: "ఆశించిన మార్కెట్ ధర (₹ ప్రతి క్వింటాల్)",
    predictedYieldPlaceholder: "అంచనా దిగుబడి (క్వింటాల్ ప్రతి ఎకరు)",
    analyzeFieldButton: "పొలాన్ని విశ్లేషించండి",
    lastScanDesc: "మీ పొలాల కోసం తాజా డ్రోన్ చిత్రాలు, పురుగుల ప్రమాదం, పోషక ఒత్తిడి మరియు దిగుబడి అంచనాను చూడండి.",
    lastScanAnalysis: "మొత్తం విస్తీర్ణంలో సుమారు 18% ప్రాంతంలో స్వల్ప ఒత్తిడి గుర్తించబడింది, ముఖ్యంగా ఉత్తర వైపు. 3 రోజుల్లో నైట్రోజన్ స్ప్రే చేయాలని సిఫార్సు చేస్తాము.",
    healthSummaryTitle: "ఆరోగ్య సారాంశం",
    yieldPredictionTitle: "దిగుబడి అంచనా",
    pestRiskMedium: "పురుగుల ప్రమాదం: మధ్యస్థం (ఉత్తర వైపు పాచెస్)",
    nutrientStressLow: "పోషక ఒత్తిడి: తక్కువ",
    expectedYieldLine: "ఆశించిన దిగుబడి: 22–26 క్వింటాల్/ఎకరు",
    profitHint: "ఈ దిగుబడి కోసం ఆశించిన ఆదాయం మరియు లాభాన్ని చూడటానికి లాభ కాలిక్యులేటర్ పేజీని ఉపయోగించండి.",
    dronePlaceholder: "డ్రోన్ చిత్రం / NDVI మ్యాప్ ప్లేస్‌హోల్డర్",
    homeTitle: "మీ పొలాలు",
    fieldHealthy: "ఆరోగ్యకరమైన పంట",
    fieldDetailTitlePrefix: "పొలం #",
    fieldDetailTitleSuffix: "– ఆరోగ్యం & దిగుబడి",
    newFieldName: "కొత్త ప్లాట్",
    openProfitCalculator: "లాభ కాలిక్యులేటర్‌ను తెరవండి",
    scanItemCompleted: "పూర్తైంది",
    scanItemRequested: "అభ్యర్థించబడింది",
    criticalScanTip: "క్లిష్టమైన దశల్లో స్కాన్‌లను పొందండి: ప్రారంభంలో, మధ్య-పంట దశలో మరియు కోత ముందు.",
  },

  mr: {
    appName: "AgriVistaar",
    tagline: "शेतकऱ्याचा साथी",
    precisionAg: "अचूक शेती • ड्रोन विश्लेषण",
    login: "लॉगिन",
    signup: "साइन अप",
    welcome: "नमस्कार, शेतकरी जी 👋",
    welcomeFarmer: "नमस्कार, शेतकरी जी",
    requiredField: "आवश्यक",
    passwordMismatch: "पासवर्ड जुळत नाहीत",
    wrongPassword: "चुकीचा पासवर्ड",
    userNotFound: "वापरकर्ता सापडला नाही",
    userAlreadyExists: "वापरकर्ता आधीच अस्तित्वात आहे",
    signupFailed: "साइन अप अयशस्वी झाले. पुन्हा प्रयत्न करा.",
    loginFailed: "लॉगिन अयशस्वी झाले. पुन्हा प्रयत्न करा.",
    loadError: "डॅशबोर्ड लोड होऊ शकला नाही",
    loading: "लोड होत आहे...",
    scanSubmitError: "स्कॅन विनंती अयशस्वी झाली. पुन्हा प्रयत्न करा.",
    getStarted: "सुरू करा",
    createAccount: "मोफत खाते तयार करा",
    heroText: "आकाशातून किडे, पोषक ताण आणि उत्पन्न पहा, आणि जास्तीत जास्त नफ्यासाठी तुमचे पीक विकण्याची सर्वोत्तम वेळ आणि मंडी जाणून घ्या.",
    droneInsights: "ड्रोन अंतर्दृष्टी",
    droneInsightsDesc: "किडे आणि ताण लवकर शोधा",
    mandiTiming: "स्मार्ट मंडी वेळ",
    mandiTimingDesc: "किंमती सर्वाधिक असताना विका",
    yieldPrediction: "उत्पन्न अंदाज",
    yieldPredictionDesc: "कापणीची योजना परिपूर्णपणे करा",
    farmers: "शेतकरी",
    acresMonitored: "एकर निरीक्षण केले",
    accuracy: "अचूकता",
    aiSupport: "AI समर्थन",
    liveMonitoring: "थेट निरीक्षण",
    updatedAgo: "2 तास आधी अद्यतनित केले",
    droneView: "पीक शेताचे ड्रोन दृश्य",
    aiPowered: "(एआई-संचालित विश्लेषण)",
    pestRisk: "किड धोका",
    nutrient: "पोषक",
    yield: "उत्पन्न",
    low: "कमी",
    onArea: "80% क्षेत्रावर",
    mediumN: "मध्यम नाइट्रोजन",
    stressNorth: "उत्तरेला ताण",
    perAcre: "प्रति एकर",
    myFields: "माझी शेतं",
    clickField: "ड्रोन हेल्थ मॅप आणि उत्पन्न पाहण्यासाठी कोणत्याही शेतावर टॅप करा.",
    myScans: "माझे स्कॅन",
    lastScan: "शेवटचा स्कॅन",
    farmerDroneDashboard: "शेतकरी ड्रोन डॅशबोर्ड",
    myFieldsTitle: "माझी शेतं",
    myFieldsHelp: "शेताचा स्कॅन स्टेटस आणि तपशील पाहण्यासाठी शेतावर टॅप करा.",
    noFields: "अजून कोणतेही शेत जोडलेले नाही.",
    fieldCrop: "पीक:",
    lastScanLabel: "शेवटचा स्कॅन:",
    notScanned: "अजून स्कॅन केलेले नाही",
    myScansTitle: "माझे ड्रोन स्कॅन",
    myScansHelp: "अलीकडच्या सर्व ड्रोन स्कॅनची यादी. पूर्ण अहवाल पाहण्यासाठी कोणत्याही ओळीवर टॅप करा.",
    noScans: "अजून कोणताही स्कॅन नाही.",
    fieldFallback: "शेत",
    analysisPendingShort: "विश्लेषण सुरू आहे",
    lastScanTitle: "शेवटचा स्कॅन",
    lastScanField: "शेत:",
    lastScanStatus: "स्थिती:",
    lastScanDate: "तारीख:",
    analysisPendingLong: "विश्लेषण सुरू आहे. फोटो अपलोड आणि प्रोसेस झाल्यानंतर अहवाल तयार होईल.",
    tapToViewReport: "पूर्ण अहवाल पाहण्यासाठी टॅप करा",
    requested: "स्कॅनची विनंती केली",
    imagesUploaded: "विश्लेषण सुरू आहे",
    completed: "अहवाल तयार",
    unknownStatus: "स्थिती माहित नाही",
    healthyCropLabel: "पीक स्थिती: निरोगी",
    cropLabel: "पीक:",
    sowingDateLabel: "पेरणीची तारीख:",
    requestScanButton: "ड्रोन स्कॅनची विनंती करा",
    fieldNotFound: "शेत सापडले नाही.",
    requestScanTitle: "ड्रोन स्कॅन विनंती",
    requestScanDesc: "कोणते शेत आणि पीक टप्पा स्कॅन करायचा ते निवडा. ही विनंती तुमच्या FPO / ड्रोन ऑपरेटरकडे जाईल.",
    fieldLabel: "शेत",
    selectFieldPlaceholder: "शेताचे नाव किंवा आयडी लिहा / तपासा",
    fieldRequired: "कृपया शेताचे नाव किंवा आयडी भरा.",
    stageLabel: "पीक अवस्था",
    cropStageLabel: "पीक टप्पा",
    selectStagePlaceholder: "पीक अवस्था निवडा",
    stageEarly: "सुरुवातीची वाढ",
    stageMid: "मध्य अवस्था",
    stagePreHarvest: "कापणीपूर्व अवस्था",
    stageRequired: "कृपया पीक अवस्था निवडा.",
    dateLabel: "इच्छित स्कॅन तारीख",
    dateRequired: "कृपया तारीख निवडा.",
    preferredDateLabel: "पसंतीची तारीख",
    notesLabel: "ड्रोन पायलटसाठी नोंदी",
    notesPlaceholder: "दृश्यमान समस्या किंवा सूचना असल्यास लिहा (पर्यायी).",
    pilotNotesLabel: "पायलटसाठी नोट्स (पर्यायी)",
    scanRequestSuccess: "आपली ड्रोन स्कॅन विनंती पाठवली आहे.",
    submitScanRequest: "स्कॅन विनंती सबमिट करा",
    submitScanButton: "स्कॅन विनंती सबमिट करा",
    loginTo: "लॉगिन करा",
    phone: "फोन नंबर / ईमेल",
    phonePlaceholder: "फोन नंबर किंवा ईमेल प्रविष्ट करा",
    password: "पासवर्ड / OTP",
    passwordPlaceholder: "••••••",
    forgotPassword: "पासवर्ड विसरलात?",
    support: "समर्थन: 1800-XXX-XXXX",
    newTo: "नवीन आहात",
    loginDesc: "तुमच्या शेतासाठी तयार केलेले ड्रोन स्कॅन, पीक आरोग्य आणि मंडी संकेत पाहण्यासाठी तुमचा नोंदणीकृत फोन किंवा ईमेल वापरा.",
    lastScanAnalysis: "एकूण क्षेत्रफळाच्या सुमारे 18% भागात सौम्य ताण आढळला, मुख्यतः उत्तर बाजूला. 3 दिवसांच्या आत नायट्रोजन फवारणी करण्याची शिफारस आहे.",
    scanItemCompleted: "पूर्ण",
    scanItemRequested: "विनंती केलेले",
    join: "सामील व्हा",
    newFarmerAccount: "नवीन शेतकरी खाते",
    signupDesc: "तुमच्या शेतांसाठी AI-संचालित किड इशारे, पोषक ताण नकाशे आणि मंडी वेळ सूचना मिळवा.",
    name: "नाव",
    namePlaceholder: "शेतकऱ्याचे नाव",
    phoneNumber: "फोन नंबर / ईमेल",
    phoneDesc: "OTP, लॉगिन आणि पीक इशाऱ्यांसाठी",
    district: "जिल्हा",
    districtPlaceholder: "उदा. सीतापूर",
    state: "राज्य",
    statePlaceholder: "उत्तर प्रदेश",
    passwordLabel: "पासवर्ड",
    passwordSignupPlaceholder: "मजबूत पासवर्ड निवडा",
    createAccountBtn: "खाते तयार करा",
    agreeText: "साइन अप करून तुम्ही तुमच्या मोबाईल नंबर किंवा ईमेलवर महत्त्वाचे पीक इशारे प्राप्त करण्यास सहमत आहात.",
    alreadyHaveAccount: "आधीच खाते आहे?",
    confirmPasswordLabel: "पासवर्डची पुष्टी करा",
    confirmPasswordPlaceholder: "पासवर्ड पुन्हा प्रविष्ट करा",
    todaySnapshot: "तुमच्या शेतांचा, आरोग्याचा आणि उत्पन्नाचा आजचा स्नॅपशॉट येथे आहे.",
    droneUpdated: "ड्रोन स्कॅन 2 तास आधी अद्यतनित केले • हवामान: फवारणीसाठी चांगले",
    totalFields: "एकूण शेते",
    atRiskFields: "धोक्यात असलेली शेते",
    avgYield: "सरासरी उत्पन्न (क्विंटल/एकर)",
    expectedIncome: "अपेक्षित उत्पन्न (₹)",
    addNewField: "नवीन शेत जोडा",
    wheatNorth: "उत्तर गहूचे शेत",
    moderatePestRisk: "मध्यम किड धोका",
    mustardEast: "मोहरी – पूर्व प्लॉट",
    healthy: "निरोगी",
    paddySouth: "सखल जमिनीचा भात",
    nutrientStress: "पोषक ताण",
    todayMandi: "आजचा मंडी संकेत",
    mandiDesc: "गेल्या 30 दिवसांच्या मंडी डेटा आणि अंदाजित किमतींवर आधारित.",
    wheat: "गहू",
    sellNow: "आता विका ↑",
    mustard: "मोहरी",
    hold1Week: "1 आठवडा धरून ठेवा",
    paddy: "भात",
    priceFalling: "किंमत घटत आहे ↓",
    logout: "लॉग आउट",
    dashboard: "डॅशबोर्ड",
    droneUpload: "ड्रोन अपलोड",
    profit: "नफा",
    scanGeneralTip: "हंगामातील फक्त 2-3 महत्त्वाच्या टप्प्यांवर उच्च-मूल्य ड्रोन स्कॅन करा; दर आठवड्याला ड्रोन उडवण्याची गरज नाही.",
    scanRecommendedPrefix: "या आठवड्यात स्कॅनची शिफारस केली आहे ",
    scanRecommendedSuffix: " (महत्त्वाचा वाढीचा टप्पा).",
    scansThisSeason: "{{done}}/{{total}} या हंगामात स्कॅन",
    scanDueNow: "आता स्कॅन देय आहे ({{stage}} टप्पा)",
    nextScanInDays: "पुढील स्कॅन: {{stage}} ~{{days}} दिवसांत",
    dashboardTitle: "शेतकरी ड्रोन डॅशबोर्ड",
    mainSathi: "मुख्य साथी — तुमचा फार्मिंग असिस्टंट",
    cropHealth: "पिकआरोग्य व कीट समस्या",
    droneScan: "ड्रोन स्कॅन अहवाल",
    useApp: "अ‍ॅप वापरा",
    selectLang: "भाषा निवडा — हिंदी, इंग्रजी किंवा इतर",
    calculateButton: "पीक नफा कॅल्क्युलेटर",
    allFieldsRequired: "कृपया सर्व फील्ड भरा.",
    positiveValuesRequired: "सर्व मूल्ये ० पेक्षा जास्त असणे आवश्यक आहे.",
    totalYieldLabel: "एकूण उत्पादन",
    totalRevenueLabel: "एकूण उत्पन्न",
    totalCostLabel: "एकूण खर्च",
    netProfitLabel: "निव्वळ नफा",
    quintalUnit: "क्विंटल",
    profitCalculatorHint: "अपेक्षित बाजारभावावर आधारित अंदाज. प्रत्यक्ष निकाल वेगळे असू शकतात.",
    analysisCompleteMessage: "शेताचे विश्लेषण पूर्ण झाले! निकालांसाठी तुमचे डॅशबोर्ड पहा.",
    profitCalculatorTitle: "पीक नफा कॅल्क्युलेटर",
    profitCalculatorDesc: "तुमच्या पिकाचे उत्पादन, उत्पन्न आणि नफा याचा अंदाज लावा.",
    areaPlaceholder: "क्षेत्रफळ (एकर)",
    totalCostPlaceholder: "एकूण खर्च (₹)",
    expectedPricePlaceholder: "अपेक्षित बाजार किंमत (₹ प्रति क्विंटल)",
    predictedYieldPlaceholder: "अंदाजे उत्पादन (क्विंटल प्रति एकर)",
    uploadDroneTitle: "ड्रोन प्रतिमा अपलोड करा",
    uploadDroneDesc: "किड, ताण आणि उत्पन्न विश्लेषणासाठी AI ला शेत प्रतिमा पाठवा.",
    aiAssistantTitle: "AI शेत सहाय्यक",
    chatWelcome: "नमस्कार! तुमच्या पिकाबद्दल, उत्पन्नाबद्दल किंवा किमतींबद्दल मला विचारा.",
    chatDemoReply: "डेमो उत्तर: मी तुमचे शेत आणि किमती विश्लेषण करेन.",
    chatPlaceholder: "तुमचा प्रश्न इंग्रजी/मराठीत टाइप करा...",
    send: "पाठवा",
    askSathi: "साथीला विचारा",
    forgotPasswordTitle: "पासवर्ड विसरलात?",
    forgotPasswordDesc: "तुमच्या AgriVistaar खात्यासाठी नवीन पासवर्ड तयार करा.",
    saveNewPassword: "नवीन पासवर्ड सेव्ह करा",
    viewLastScanButton: "शेवटचा स्कॅन अहवाल पहा",
    analyzeFieldButton: "शेताचे विश्लेषण करा",
    lastScanDesc: "तुमच्या शेतांसाठी नवीनतम ड्रोन प्रतिमा, किड धोका, पोषक ताण आणि उत्पन्न अंदाज पहा.",
    healthSummaryTitle: "आरोग्य सारांश",
    yieldPredictionTitle: "उत्पन्न अंदाज",
    pestRiskMedium: "किड धोका: मध्यम (उत्तर बाजूला ठिपके)",
    nutrientStressLow: "पोषक ताण: कमी",
    expectedYieldLine: "अपेक्षित उत्पन्न: 22–26 क्विंटल/एकर",
    profitHint: "या उत्पन्नासाठी अपेक्षित उत्पन्न आणि नफा पाहण्यासाठी नफा कॅल्क्युलेटर पृष्ठ वापरा.",
    dronePlaceholder: "ड्रोन प्रतिमा / NDVI नकाशा प्लेसहोल्डर",
    homeTitle: "तुमची शेते",
    fieldHealthy: "निरोगी पीक",
    fieldDetailTitlePrefix: "शेत #",
    fieldDetailTitleSuffix: "– आरोग्य आणि उत्पन्न",
    openProfitCalculator: "नफा कॅल्क्युलेटर उघडा",
    newFieldName: "नवीन प्लॉट",
    criticalScanTip: "महत्त्वाच्या टप्प्यांवर स्कॅन मिळवा: सुरुवातीला, मध्य-पीक टप्प्यावर आणि कापणीपूर्वी.",
    dropImageHere: "ड्रोन प्रतिमा येथे सोडा",
dropImageOr: "किंवा",
browseLink: "ब्राउझ करा",
dropImageToSelect: "करून निवडा",
supportedFormats: "समर्थित: JPG, PNG, WEBP",
orDivider: "किंवा",
chooseFileButton: "फाईल निवडा",
analyzingStatus: "विश्लेषण होत आहे...",
analysisResultTitle: "विश्लेषण निकाल",
removeFile: "काढा",
infoCropHealth: "पीक आरोग्य",
infoCropHealthDesc: "एनडीवीआई (NDVI) विश्लेषण",
infoPestDetection: "किड शोध",
infoPestDetectionDesc: "AI स्कॅन",
infoMoisture: "ओलावा नकाशा",
infoMoistureDesc: "ताण क्षेत्रे",
  },
};

// eslint-disable-next-line react-refresh/only-export-components
export const languages = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिंदी" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
];

export const LanguageProvider = ({ children }) => {
  const stored =
    typeof window !== "undefined"
      ? localStorage.getItem("appLanguage")
      : null;

  const [language, setLanguage] = useState(stored || "en");

  const t = (key, vars) => {
    let value =
      translations[language]?.[key] ??
      translations.en[key] ??
      key;

    if (vars && typeof value === "string") {
      Object.entries(vars).forEach(([k, v]) => {
        value = value.replace(`{{${k}}}`, String(v));
      });
    }
    return value;
  };

  const changeLanguage = (langCode) => {
    setLanguage(langCode);
    localStorage.setItem("appLanguage", langCode);
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage: changeLanguage, changeLanguage, t, languages }}
    >
      {children}
    </LanguageContext.Provider>
  );
};